### ISSUE TITLE
Maximum number of backups

### ISSUE THREAD

**Issue by arnoson** [sylvainjule/kirby-backups#7]
It would be great to be able to specify a maximum number of backups. If this number is reached the oldest backup would be deleted automatically each time a new backup is made. If your are interested in this feature I can create a PR.

**Comment by sylvainjule** [comment]
Now available with:

```php
'sylvainjule.backups.maximum' => 10, // or any integer, default is false
```

**Comment by arnoson** [comment]
awesome, thanks!
