### ISSUE TITLE
Compatiblity with Kirby Janitor v3+

### ISSUE THREAD

**Issue by tobimori** [sylvainjule/kirby-backups#8]
<img width="640" alt="CleanShot 2022-12-18 at 14 49 17@2x" src="https://user-images.githubusercontent.com/29142128/208301946-409011b6-a5b3-4fde-8046-5d50077f344c.png">
throws this error when trying to open the area.

**Comment by luglio7** [comment]
same here

**Comment by kosmar** [comment]
same

**Comment by sylvainjule** [comment]
Compatibility issue is fixed! 
**Breaking change:** the prefix option name needs to be updated.

```
// from
'bnomei.janitor.backupzip.prefix' => 'backup-',

// to
'sylvainjule.backups.prefix' => 'backup-',
```
