### ISSUE TITLE
maximum backups ignored when using cron job with janitor

### ISSUE THREAD

**Issue by arnoson** [sylvainjule/kirby-backups#9]
I have setup maximum backups as shown in the readme but the option is ignored when I use a cron job with kirby janitor. So I guess when not using this plugin ui/api to create backups only janitor is involved. So I would have to create a cutsom web hook endpoint and copy the code from the `backups/create-backup` api route? Or is there also a way to trigger a backup via a web hook using this plugin directly?

**Comment by sylvainjule** [comment]
The plugin now exposes a webhook: `https://your.domain/backups-webhook/{janitor.secret}/create-backup`

**Comment by arnoson** [comment]
awesome, thank you!
